name: Retrain Model

on:
  schedule:
    - cron: '0 0 * * 0'   # every Sunday
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements_backend.txt

    - name: Run retraining
      run: |
        python retrain.py